baseURL = "https://raysuids.dpdns.org/"
title = "Ray's Blog"
enableRobotsTXT = true

# Hugo 0.128+ 的分页写法
[pagination]
  pagerSize = 10

# 主题（用模块路径；不要改 /themes 目录）
theme = "github.com/adityatelange/hugo-PaperMod"

# 用 Hugo Modules 引入主题
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  # 关闭暗色模式（你反馈暗色观感很差）
  defaultTheme = "light"
  disableThemeToggle = true

  # 文章页与列表的常用开关
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowShareButtons = true

  # 底部社交
  [[params.socialIcons]]
    name = "github"
    url  = "https://github.com/你的GitHub用户名"
  [[params.socialIcons]]
    name = "rss"
    url  = "/index.xml"

# 顶部菜单
[menu]
  [[menu.main]]
    name = "主页"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "归档"
    url  = "/archives/"
    weight = 2
  [[menu.main]]
    name = "标签"
    url  = "/tags/"
    weight = 3
  [[menu.main]]
    name = "关于"
    url  = "/about/"
    weight = 4
  [[menu.main]]
    name = "留言板"
    url  = "/guestbook/"
    weight = 5
  [[menu.main]]
    name = "新闻"
    url  = "/news/"
    weight = 6
   [[menu.main]]
    name = "管理"
    url  = "/admin/"
    weight = 99
    [menu]
  # 其他菜单...
 
# 允许 Markdown 中的原生 HTML（防止表单/按钮被转义）
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
